# Generated by Django 5.2.17 on 2026-09-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video'), ('cognitive', 'Cognitive')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='assessment_inputs/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['assessment', 'input_type'], name='assessment_input_type_idx'), models.Index(fields=['status', 'created_at'], name='assessment_input_status_idx')],
            },
        ),
    ]
